<?php

use Illuminate\Database\Seeder;

class AdvisorsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'1',  'name'=>'Mark J. Palmer', 'phone'=>'614-228-4300', 'email'=>'', 'company'=>'The Joseph Group Capital Management', 'address1'=>'300 Marconi Boulevard', 'address2'=>'', 'city'=>'Columbus', 'st'=>'OH', 'zip'=>'43215', 'url'=>'http://www.josephgroup.com', 'minimum_fee'=>'0', 'feeCalculation'=>'0', 'lat'=>'39.9681326', 'lng'=>'-83.0048595', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=435902', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'2',  'name'=>'Greg R. Grabovac, JD', 'phone'=>'614-296-8879', 'email'=>'', 'company'=>'G2 Capital Management', 'address1'=>'448 W. Nationwide Blvd.', 'address2'=>'Loft 106', 'city'=>'Columbus', 'st'=>'OH', 'zip'=>'43215', 'url'=>'http://www.g2capital.net', 'minimum_fee'=>'5000', 'feeCalculation'=>'0', 'lat'=>'39.968788', 'lng'=>'-83.0000941', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=453058', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'3',  'name'=>'Randall T. Gerber', 'phone'=>'614-431-4343', 'email'=>'', 'company'=>'Gerber, LLC', 'address1'=>'121 E. Nationwide Blvd.', 'address2'=>'', 'city'=>'Columbus', 'st'=>'OH', 'zip'=>'43215', 'url'=>'http://www.gerberclarity.com', 'minimum_fee'=>'0', 'feeCalculation'=>'0', 'lat'=>'39.9687944', 'lng'=>'-82.9981827', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=436593', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'4',  'name'=>'Mark Doyle', 'phone'=>'630-701-9359', 'email'=>'', 'company'=>'Clement Street Capital', 'address1'=>'600 W 22nd St', 'address2'=>'Suite 308', 'city'=>'Oak Brook', 'st'=>'IL', 'zip'=>'60523', 'url'=>'http://www.clementstreetcapital.com', 'minimum_fee'=>'0', 'feeCalculation'=>'0', 'lat'=>'41.8481432', 'lng'=>'-87.9346045', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=422380', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'5',  'name'=>'Morgan Pearsall', 'phone'=>'630-828-2199', 'email'=>'mpearsall@mgp-wealth.com', 'company'=>'MGP Wealth Management', 'address1'=>'800 Enterprise Dr.', 'address2'=>'Suite 212', 'city'=>'Oak Brook', 'st'=>'IL', 'zip'=>'60523', 'url'=>'http://www.mgp-wealth.com', 'minimum_fee'=>'10000', 'feeCalculation'=>'0', 'lat'=>'41.8477172', 'lng'=>'-87.9399372', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=433019', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'6',  'name'=>'John Maguire', 'phone'=>'630-654-8382', 'email'=>'john@maguireasset.org', 'company'=>'Maguire Asset Management', 'address1'=>'15 Spinning Wheel Dr', 'address2'=>'Suite 210', 'city'=>'Hinsdale', 'st'=>'IL', 'zip'=>'60521', 'url'=>'http://www.maguireasset.org', 'minimum_fee'=>'2500', 'feeCalculation'=>'0', 'lat'=>'41.8208896', 'lng'=>'-87.9189992', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=447743', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'7',  'name'=>'James H. Taylor CFP', 'phone'=>'614-235-6710', 'email'=>'jamie@taylorfinancialmanagementinc.com', 'company'=>'Taylor Financial Management', 'address1'=>'2700 E. Main Street', 'address2'=>'Suite 105', 'city'=>'Bexley', 'st'=>'OH', 'zip'=>'43209', 'url'=>'http://www.taylorfinancialmanagmentinc.com', 'minimum_fee'=>'0', 'feeCalculation'=>'0', 'lat'=>'39.9572012', 'lng'=>'-82.9265675', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=450326', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'8',  'name'=>'Michael R. Harding', 'phone'=>'614-985-3678', 'email'=>'harding@hardingfinancialgroup.com', 'company'=>'Harding Financial Group, LLC', 'address1'=>'200 East Campus View Blvd', 'address2'=>'Suite 200', 'city'=>'Columbus', 'st'=>'OH', 'zip'=>'43235', 'url'=>'http://www.hardingfinancialgroup.com', 'minimum_fee'=>'0', 'feeCalculation'=>'0', 'lat'=>'40.119413', 'lng'=>'-83.0103409', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=435809', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'9',  'name'=>'Sequoia Financial Advisors LLC', 'phone'=>'888-225-3777', 'email'=>'info@sequoia-financial.com', 'company'=>'Sequoia Financial Advisors LLC', 'address1'=>'3500 Embassy Parkway', 'address2'=>'', 'city'=>'Akron', 'st'=>'OH', 'zip'=>'44333', 'url'=>'http://www.sequoia-financial.com', 'minimum_fee'=>'0', 'feeCalculation'=>'0', 'lat'=>'41.1480661', 'lng'=>'-81.6379652', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=448570', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'10', 'name'=>'Victor Moy CFA', 'phone'=>'513-247-6102', 'email'=>'', 'company'=>'Moy Investment Management LLC', 'address1'=>'300 E. Business Way', 'address2'=>'', 'city'=>'Cincinnati', 'st'=>'OH', 'zip'=>'45241', 'url'=>'', 'minimum_fee'=>'0', 'feeCalculation'=>'0', 'lat'=>'39.284778', 'lng'=>'-84.3671741', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=413886', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'11', 'name'=>'John A. Davidson', 'phone'=>'614-395-1295', 'email'=>'', 'company'=>'KylesHill Financial Planning', 'address1'=>'3400 N. High St.', 'address2'=>'Suite 210', 'city'=>'Columbus', 'st'=>'OH', 'zip'=>'43202', 'url'=>'http://www.lifelongadvisors.com', 'minimum_fee'=>'2000', 'feeCalculation'=>'0', 'lat'=>'40.0312007', 'lng'=>'-83.0153941', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=454637', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'12', 'name'=>'Molly Mae Grubb', 'phone'=>'614-461-3205', 'email'=>'', 'company'=>'Grubb Wealth Management LLC', 'address1'=>'454 E Main St.', 'address2'=>'Suite 215', 'city'=>'Columbus', 'st'=>'OH', 'zip'=>'43215', 'url'=>'http://www.grubbwealthmanagement.com', 'minimum_fee'=>'0', 'feeCalculation'=>'0', 'lat'=>'39.9577936', 'lng'=>'-82.9872501', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=453542', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'13', 'name'=>'Tony D\'Amico', 'phone'=>'440-572-5552', 'email'=>'', 'company'=>'Fidato Wealth', 'address1'=>'10749 Pearl Rd', 'address2'=>'#1B', 'city'=>'Strongsville', 'st'=>'OH', 'zip'=>'44136', 'url'=>'http://www.fidatowealth.com', 'minimum_fee'=>'3000', 'feeCalculation'=>'0', 'lat'=>'41.3325474', 'lng'=>'-81.8358966', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=429368', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'14', 'name'=>'John H. Bair', 'phone'=>'440-627-6985', 'email'=>'', 'company'=>'Ascend Wealth Advisors, LLC', 'address1'=>'7750 Town Centre Dr.', 'address2'=>'Suite 800', 'city'=>'Broadview Heights', 'st'=>'OH', 'zip'=>'44147', 'url'=>'http://ascendwealthadvisors.com', 'minimum_fee'=>'0', 'feeCalculation'=>'0', 'lat'=>'41.3121434', 'lng'=>'-81.6818363', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=449742', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'15', 'name'=>'Keith Cantrell, CFP', 'phone'=>'847-397-3000', 'email'=>'nsnodgrass@evanstonadvisors.com', 'company'=>'Evanston Advisors', 'address1'=>'1300 E. Woodfield Road', 'address2'=>'Suite 300', 'city'=>'Schaumburg', 'st'=>'IL', 'zip'=>'60173', 'url'=>'http://www.evanstonadvisors.com', 'minimum_fee'=>'5000', 'feeCalculation'=>'0', 'lat'=>'42.0436967', 'lng'=>'-88.0461544', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=431572', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'16', 'name'=>'Matthew E. Shaffer', 'phone'=>'614-891-1200', 'email'=>'info@shaffercapital.net', 'company'=>'Shaffer Capital Advisors, LLC', 'address1'=>'550 Polaris Parkway', 'address2'=>'Suite 540', 'city'=>'Westerville', 'st'=>'OH', 'zip'=>'43082', 'url'=>'http://www.shaffercapital.net', 'minimum_fee'=>'0', 'feeCalculation'=>'0', 'lat'=>'40.1479748', 'lng'=>'-82.9479938', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=447493', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'17', 'name'=>'John C. Lynch CPA,CFA, CFP', 'phone'=>'614-791-8884', 'email'=>'jlynch@lynchfinancialgroup.com', 'company'=>'Lynch Financial Group, LLC', 'address1'=>'5880 Sawmill Rd.', 'address2'=>'Suite 204', 'city'=>'Dublin', 'st'=>'OH', 'zip'=>'43017', 'url'=>'http://www.lynchfinancialgroup.com', 'minimum_fee'=>'5000', 'feeCalculation'=>'0', 'lat'=>'40.0875149', 'lng'=>'-83.0903079', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=436685', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'18', 'name'=>'Joseph Messinger CFP', 'phone'=>'614-754-7805', 'email'=>'info@capstonewealthpartners.com', 'company'=>'Capstone Wealth Partners, LTD', 'address1'=>'6037 Frantz Rd.', 'address2'=>'Suite 104', 'city'=>'Dublin', 'st'=>'OH', 'zip'=>'43017', 'url'=>'http://www.capstonewealthpartners.com', 'minimum_fee'=>'0', 'feeCalculation'=>'0', 'lat'=>'40.0907178', 'lng'=>'-83.1254266', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=447436', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'19', 'name'=>'Richard Walen', 'phone'=>'419-885-2599', 'email'=>'', 'company'=>'Walen Financial Group', 'address1'=>'4149 N. Holland Sylvania Road', 'address2'=>'Suite 104', 'city'=>'Toledo', 'st'=>'OH', 'zip'=>'43623', 'url'=>'http://www.rwalen.com/index.php', 'minimum_fee'=>'0', 'feeCalculation'=>'0', 'lat'=>'41.6933201', 'lng'=>'-83.6881033', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=433653', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'20', 'name'=>'William G. Henderly, CFA', 'phone'=>'614-389-4646', 'email'=>'info@nvestwealth.com', 'company'=>'Nvest Wealth Strategies, Inc.', 'address1'=>'10268 Sawmill Parkway', 'address2'=>'', 'city'=>'Powell', 'st'=>'OH', 'zip'=>'43065', 'url'=>'http://www.nvestwealth.com', 'minimum_fee'=>'0', 'feeCalculation'=>'0', 'lat'=>'40.1486676', 'lng'=>'-83.0938961', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=417879', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'21', 'name'=>'Christopher J. Henneforth', 'phone'=>'614-885-9980', 'email'=>'mkkashner@levelpartners.com', 'company'=>'Level Partners Management Inc', 'address1'=>'600 Morrison Rd.', 'address2'=>'', 'city'=>'Columbus', 'st'=>'OH', 'zip'=>'43230', 'url'=>'http://www.levelpartners.com', 'minimum_fee'=>'0', 'feeCalculation'=>'0', 'lat'=>'40.003019', 'lng'=>'-82.860196', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=358159', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'22', 'name'=>'Daniel Betzel', 'phone'=>'614-472-4510', 'email'=>'dan@betzelwealthadvisors.com', 'company'=>'Betzel Wealth Advisors, LLC', 'address1'=>'81 Mill St.', 'address2'=>'', 'city'=>'Gahanna', 'st'=>'OH', 'zip'=>'43230', 'url'=>'http://www.betzelwealthadvisors.com', 'minimum_fee'=>'0', 'feeCalculation'=>'0', 'lat'=>'40.0200051', 'lng'=>'-82.8800845', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=456085', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'23', 'name'=>'Landon R. Jones CFP', 'phone'=>'440-248-3355', 'email'=>'', 'company'=>'LJR Wealth Management, LLC', 'address1'=>'60 Franklin\'s Row', 'address2'=>'', 'city'=>'Solon', 'st'=>'OH', 'zip'=>'44139', 'url'=>'http://www.lrjwealth.com', 'minimum_fee'=>'0', 'feeCalculation'=>'0', 'lat'=>'41.3616694', 'lng'=>'-81.4494811', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=440996', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'24', 'name'=>'James A. Lindner CFP', 'phone'=>'614-799-8668', 'email'=>'jlindner@retirement-strategies.com', 'company'=>'Retirement Strategies, LTD.', 'address1'=>'5060 Parkcenter Ave.', 'address2'=>'Suite A', 'city'=>'Dublin', 'st'=>'OH', 'zip'=>'43017', 'url'=>'http://www.retirement-strategies.com', 'minimum_fee'=>'0', 'feeCalculation'=>'0', 'lat'=>'40.0796309', 'lng'=>'-83.1260433', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=419810', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'25', 'name'=>'Helyn Bolanis', 'phone'=>'419-885-1130', 'email'=>'hbolanis@parlan.com', 'company'=>'Parlan Financial Corporation', 'address1'=>'6011 Renaissance Pl.', 'address2'=>'Unit 3', 'city'=>'Toledo', 'st'=>'OH', 'zip'=>'43623', 'url'=>'http://www.parlan.com', 'minimum_fee'=>'0', 'feeCalculation'=>'0', 'lat'=>'41.6960784', 'lng'=>'-83.6870021', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=420720', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'26', 'name'=>'Jack McKewen III', 'phone'=>'614-888-2222', 'email'=>'info@jhmckewen.com', 'company'=>'J.H. McKewen III & Associates', 'address1'=>'647 Park Meadow Rd.', 'address2'=>'Suite 1', 'city'=>'Westerville', 'st'=>'OH', 'zip'=>'43081', 'url'=>'http://www.jhmckewen.com', 'minimum_fee'=>'50', 'feeCalculation'=>'0', 'lat'=>'40.10884', 'lng'=>'-82.9370697', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=449934', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'27', 'name'=>'Thomas Mangia', 'phone'=>'614-760-3713', 'email'=>'tmangia@investdcm.com', 'company'=>'Delta Capital Management', 'address1'=>'545 Metro Place South', 'address2'=>'Suite 110', 'city'=>'Dublin', 'st'=>'OH', 'zip'=>'43017', 'url'=>'http://www.investdcm.com', 'minimum_fee'=>'0', 'feeCalculation'=>'0', 'lat'=>'40.0929996', 'lng'=>'-83.1323315', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=409796', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'28', 'name'=>'John T. Ross', 'phone'=>'419-842-1505', 'email'=>'', 'company'=>'Integrated Financial Resources, Inc.', 'address1'=>'7261 West Central Avenue', 'address2'=>'', 'city'=>'Toledo', 'st'=>'OH', 'zip'=>'43617', 'url'=>'', 'minimum_fee'=>'0', 'feeCalculation'=>'0', 'lat'=>'41.6730286', 'lng'=>'-83.7174513', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=437439', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'29', 'name'=>'Lee A. Kramer', 'phone'=>'800-590-7932', 'email'=>'info@cma-investments.com', 'company'=>'Capital Management Analytics, Corp.', 'address1'=>'846 Riverbend Ave.', 'address2'=>'', 'city'=>'Powell', 'st'=>'OH', 'zip'=>'43065', 'url'=>'http://www.cma-investments.com', 'minimum_fee'=>'0', 'feeCalculation'=>'0', 'lat'=>'40.1680739', 'lng'=>'-83.0380263', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=440952', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'30', 'name'=>'Brent M. Jenkins', 'phone'=>'614-766-3621', 'email'=>'brent@grantstreetwm.com', 'company'=>'Grant St. Wealth Management', 'address1'=>'155 E. Broad St', 'address2'=>'Suite 2020', 'city'=>'Columbus', 'st'=>'OH', 'zip'=>'43215', 'url'=>'http://www.grantstreetwm.com', 'minimum_fee'=>'0', 'feeCalculation'=>'1', 'lat'=>'39.9622594', 'lng'=>'-82.996637', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=418750', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'31', 'name'=>'Walter E. Moore', 'phone'=>'216-573-3725', 'email'=>'info@appaloosawm.com', 'company'=>'Appaloosa Wealth Management', 'address1'=>'5005 Rockside Rd.', 'address2'=>'Suite 600', 'city'=>'Independence', 'st'=>'OH', 'zip'=>'44131', 'url'=>'http://www.appaloosawm.com', 'minimum_fee'=>'0', 'feeCalculation'=>'1', 'lat'=>'41.398033', 'lng'=>'-81.6542275', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=426070', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'32', 'name'=>'Daniel M. Doyle', 'phone'=>'440-305-0410', 'email'=>'info@oakparwm.com', 'company'=>'Oak Park Wealth Management LLC', 'address1'=>'25935 Detroit Rd.', 'address2'=>'#103', 'city'=>'Westlake', 'st'=>'OH', 'zip'=>'44145', 'url'=>'http://www.oakparkwm.com', 'minimum_fee'=>'0', 'feeCalculation'=>'1', 'lat'=>'41.4684608', 'lng'=>'-81.9065577', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=449995', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'33', 'name'=>'John J. Jurcago', 'phone'=>'440-846-9170', 'email'=>'jurcagocpa@gmail.com', 'company'=>'Prestige Wealth Management LLC', 'address1'=>'10850 Pearl Road', 'address2'=>'Suite D5', 'city'=>'Strongsville', 'st'=>'OH', 'zip'=>'44136', 'url'=>'http://investment-advisors.credio.com/l/66253/Prestige-Wealth-Management-LLC', 'minimum_fee'=>'0', 'feeCalculation'=>'1', 'lat'=>'41.3319016', 'lng'=>'-81.8368985', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=411144', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'34', 'name'=>'Kara Downing CFP', 'phone'=>'216-654-0000', 'email'=>'kara@younitywealth.com', 'company'=>'Younity Wealth Partners', 'address1'=>'2000 Auburn Dr.', 'address2'=>'Suite 200', 'city'=>'Cleveland', 'st'=>'OH', 'zip'=>'44122', 'url'=>'http://www.YounityWealth.com', 'minimum_fee'=>'0', 'feeCalculation'=>'1', 'lat'=>'41.4563857', 'lng'=>'-81.4930865', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=427744', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'35', 'name'=>'James T. Elios', 'phone'=>'440-617-9100', 'email'=>'jim@eliosfinancial.com', 'company'=>'Elios Financial Group Inc.', 'address1'=>'30700 Center Ridge Road', 'address2'=>'', 'city'=>'Westlake', 'st'=>'OH', 'zip'=>'44145', 'url'=>'http://www.eliosfinancial.com', 'minimum_fee'=>'0', 'feeCalculation'=>'1', 'lat'=>'41.4235625', 'lng'=>'-81.9605591', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=202591', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'36', 'name'=>'James C. Nicholson Jr CFP', 'phone'=>'502-855-3160', 'email'=>'', 'company'=>'Magnate Wealth Management LLC', 'address1'=>'436 S. 7th Street', 'address2'=>'Suite 200', 'city'=>'Louisville', 'st'=>'KY', 'zip'=>'40203', 'url'=>'http://www.magnatewealth.com', 'minimum_fee'=>'0', 'feeCalculation'=>'1', 'lat'=>'38.2525229', 'lng'=>'-85.762874', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=451392', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'37', 'name'=>'Rik Saylor', 'phone'=>'513-829-8888', 'email'=>'rik@riksaylorfinancial.com', 'company'=>'Rik Saylor Financial Inc', 'address1'=>'1241 Nilles Rd.', 'address2'=>'', 'city'=>'Fairfield', 'st'=>'OH', 'zip'=>'45014', 'url'=>'http://RikSaylorFinancial.com', 'minimum_fee'=>'0', 'feeCalculation'=>'1', 'lat'=>'39.3368517', 'lng'=>'-84.5386788', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=423814', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'38', 'name'=>'Michael J. Maisel', 'phone'=>'859-655-5225', 'email'=>'maisel@legacyfinancialadvisors.com', 'company'=>'Legacy Financial Advisors Inc.', 'address1'=>'117 East Fourth Street', 'address2'=>'', 'city'=>'Covington', 'st'=>'KY', 'zip'=>'41011', 'url'=>'http://www.legacyfinancialadvisors.com', 'minimum_fee'=>'0', 'feeCalculation'=>'1', 'lat'=>'39.0872203', 'lng'=>'-84.5084726', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=425166', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'39', 'name'=>'Michael S. Bohmer', 'phone'=>'513-942-9700', 'email'=>'j.kilcoyne@hbkwealthmanagement.com', 'company'=>'HBK Wealth Management', 'address1'=>'9360 Montgomery Road', 'address2'=>'', 'city'=>'Cincinnati', 'st'=>'OH', 'zip'=>'45242', 'url'=>'http://www.HBKWealthManagement.com', 'minimum_fee'=>'0', 'feeCalculation'=>'1', 'lat'=>'39.2256505', 'lng'=>'-84.3550686', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=411945', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'40', 'name'=>'John Eiduk CPA, CFP', 'phone'=>'847-917-8981', 'email'=>'john.eiduk@eliteassetmgmt.com', 'company'=>'Elite Asset Management LLC', 'address1'=>'117 Viola Ct.', 'address2'=>'', 'city'=>'Rolling Meadows', 'st'=>'IL', 'zip'=>'60008', 'url'=>'http://eliteassetmgmt.com', 'minimum_fee'=>'0', 'feeCalculation'=>'1', 'lat'=>'42.084014', 'lng'=>'-88.049008', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=342615', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'41', 'name'=>'Cabin Gold Kim', 'phone'=>'630-578-5858', 'email'=>'cabin.kim@gmail.com', 'company'=>'Integrity Wealth Management', 'address1'=>'3821 Vardon Ct.', 'address2'=>'', 'city'=>'Woodridge', 'st'=>'IL', 'zip'=>'60517', 'url'=>'', 'minimum_fee'=>'0', 'feeCalculation'=>'1', 'lat'=>'41.7585209', 'lng'=>'-88.0766737', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=419965', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'42', 'name'=>'Dennis Purgatorio', 'phone'=>'630-705-3050', 'email'=>'dpurgatorio@cbcconsulting.com', 'company'=>'Comprehensive Retirement Plan Consultants, LLC', 'address1'=>'2021 Midwest Rd', 'address2'=>'Suite 200', 'city'=>'Oak Brook', 'st'=>'IL', 'zip'=>'60523', 'url'=>'http://cbcconsulting.com', 'minimum_fee'=>'0', 'feeCalculation'=>'1', 'lat'=>'41.8481438', 'lng'=>'-87.9717827', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=159197', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'43', 'name'=>'Scott Reynolds', 'phone'=>'630-448-5711', 'email'=>'info@sentinus.com', 'company'=>'Sentinus LLC', 'address1'=>'700 Commerce Dr.', 'address2'=>'Suite 170', 'city'=>'Oak Brook', 'st'=>'IL', 'zip'=>'60523', 'url'=>'http://www.sentinus.com', 'minimum_fee'=>'0', 'feeCalculation'=>'1', 'lat'=>'41.8514889', 'lng'=>'-87.9376409', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=429247', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'44', 'name'=>'Gregory P. Liesen', 'phone'=>'630-645-8201', 'email'=>'', 'company'=>'Geneva Financial Group LLC', 'address1'=>'118 Grant Ave.', 'address2'=>'', 'city'=>'Geneva', 'st'=>'IL', 'zip'=>'60134', 'url'=>'http://www.genevafinancialgroup.net', 'minimum_fee'=>'0', 'feeCalculation'=>'1', 'lat'=>'41.8903615', 'lng'=>'-88.3203356', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=452225', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'45', 'name'=>'Mark J. Shafer', 'phone'=>'614-402-5763', 'email'=>'mark.shafer@goodricham.com', 'company'=>'Goodrich Asset Management LLC', 'address1'=>'7325 E. Walnut St.', 'address2'=>'', 'city'=>'Westerville', 'st'=>'OH', 'zip'=>'43081', 'url'=>'http://www.goodricham.com', 'minimum_fee'=>'0', 'feeCalculation'=>'1', 'lat'=>'40.111302', 'lng'=>'-82.794675', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=437707', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'46', 'name'=>'Gary DuPont CFP', 'phone'=>'614-408-0004', 'email'=>'info@dupontwealth.com', 'company'=>'DuPont Wealth Solutions', 'address1'=>'655 Metro Place South', 'address2'=>'Suite 440', 'city'=>'Dublin', 'st'=>'OH', 'zip'=>'43017', 'url'=>'http://www.dupontwealth.com', 'minimum_fee'=>'0', 'feeCalculation'=>'1', 'lat'=>'40.0948389', 'lng'=>'-83.1352466', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=437001', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'47', 'name'=>'Bradley L. Fisher', 'phone'=>'614-866-2850', 'email'=>'info@fisherwealth.com', 'company'=>'Fisher Wealth Management LLC', 'address1'=>'81 Mill St.', 'address2'=>'Suite 300', 'city'=>'Gahanna', 'st'=>'OH', 'zip'=>'43230', 'url'=>'http://www.fisherwealth.com', 'minimum_fee'=>'0', 'feeCalculation'=>'1', 'lat'=>'40.0200051', 'lng'=>'-82.8800845', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=449979', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'48', 'name'=>'Phillip E. Bollin CFP', 'phone'=>'419-878-3934', 'email'=>'phil@bollinwealth.com', 'company'=>'Bollin Wealth Management LLC', 'address1'=>'118 W. Wayne St.', 'address2'=>'Suite B', 'city'=>'Maumee', 'st'=>'OH', 'zip'=>'43537', 'url'=>'http://www.bollinwealth.com', 'minimum_fee'=>'500', 'feeCalculation'=>'1', 'lat'=>'41.56144', 'lng'=>'-83.6541079', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=414370', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'49', 'name'=>'Alan B. Lancz', 'phone'=>'419-536-5200', 'email'=>'info@ablonline.com', 'company'=>'Alan B. Lancz and Associates, Inc.', 'address1'=>'2400 N. Reynolds Rd.', 'address2'=>'', 'city'=>'Toledo', 'st'=>'OH', 'zip'=>'43615', 'url'=>'http://www.ablonline.com', 'minimum_fee'=>'0', 'feeCalculation'=>'1', 'lat'=>'41.66603', 'lng'=>'-83.667407', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=413001', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'50', 'name'=>'Gary Lee Rothburn', 'phone'=>'419-842-0334', 'email'=>'pwcltd@privatewealthconsultants.com', 'company'=>'Private Wealth Consultants Ltd.', 'address1'=>'6591 W. Central Ave.', 'address2'=>'Suite 108', 'city'=>'Toledo', 'st'=>'OH', 'zip'=>'43617', 'url'=>'http://www.privatewealthconsultants.com', 'minimum_fee'=>'0', 'feeCalculation'=>'1', 'lat'=>'41.6749193', 'lng'=>'-83.7000652', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=423905', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'51', 'name'=>'Jeffrey D. Shoffer', 'phone'=>'419-754-3587', 'email'=>'jeff@shofferwealthmgt.com', 'company'=>'Schoffer Wealth Management LLC', 'address1'=>'P.O. Box 2965', 'address2'=>'', 'city'=>'Toledo', 'st'=>'OH', 'zip'=>'43606', 'url'=>'http://www.your-personal-cfo.com', 'minimum_fee'=>'0', 'feeCalculation'=>'1', 'lat'=>'41.6735366', 'lng'=>'-83.624201', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=452580', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'52', 'name'=>'Dock D. Treece', 'phone'=>'419-843-7744', 'email'=>'', 'company'=>'Treece Investment Advisory Corp.', 'address1'=>'6800 West Central Avenue', 'address2'=>'Unit G-1', 'city'=>'Toledo', 'st'=>'OH', 'zip'=>'43617', 'url'=>'http://www.TreeceInvestments.com', 'minimum_fee'=>'0', 'feeCalculation'=>'1', 'lat'=>'41.6753746', 'lng'=>'-83.7068686', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=420975', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'53', 'name'=>'Matthew J. Stewart', 'phone'=>'614-954-1154', 'email'=>'mstewart@forestviewfp.com', 'company'=>'Forestview Financial Partners, LLC', 'address1'=>'1967 Forestview Lane', 'address2'=>'', 'city'=>'Delaware', 'st'=>'OH', 'zip'=>'43015', 'url'=>'http://www.forestviewfp.com', 'minimum_fee'=>'5000', 'feeCalculation'=>'1', 'lat'=>'40.205793', 'lng'=>'-83.0704019', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=449160', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'54', 'name'=>'John C. Farrell, CFP, ChFC', 'phone'=>'740-363-6248', 'email'=>'', 'company'=>'John C. Farrell, CFP, ChFC', 'address1'=>'103 N Union St.', 'address2'=>'', 'city'=>'Delaware', 'st'=>'OH', 'zip'=>'43015', 'url'=>'https://www.brightscope.com/financial-planning/firm/282440/John-C-Farrell-Cfpr-ChFC/', 'minimum_fee'=>'1000', 'feeCalculation'=>'1', 'lat'=>'40.3019427', 'lng'=>'-83.065935', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=450919', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'55', 'name'=>'Scott Lucas ChFC', 'phone'=>'614-840-9770', 'email'=>'team@lucasfinancialservices.com', 'company'=>'Lucas Financial Services', 'address1'=>'947 Worthington Woods Loop Road', 'address2'=>'', 'city'=>'Worthington', 'st'=>'OH', 'zip'=>'43085', 'url'=>'http://www.lucasfinancialservices.com', 'minimum_fee'=>'0', 'feeCalculation'=>'1', 'lat'=>'40.1191189', 'lng'=>'-82.9905889', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=414027', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'56', 'name'=>'Jason M. Orsky', 'phone'=>'440-835-6550', 'email'=>'jason.orsky@jmowealthmanagement.com', 'company'=>'Jason M. Orsky Wealth Management', 'address1'=>'671 Columbia Rd.', 'address2'=>'Suite 1', 'city'=>'Westlake', 'st'=>'OH', 'zip'=>'44145', 'url'=>'http://www.jmowealthmanagement.com/', 'minimum_fee'=>'0', 'feeCalculation'=>'1', 'lat'=>'41.4767722', 'lng'=>'-81.900462', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=445703', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'57', 'name'=>'Garrett Boone', 'phone'=>'330-319-5610', 'email'=>'garrett@fortificapital.com', 'company'=>'Fortifi Capital LLC', 'address1'=>'1984 Newton St.', 'address2'=>'', 'city'=>'Akron', 'st'=>'OH', 'zip'=>'44305', 'url'=>'http://www.fortificapital.com', 'minimum_fee'=>'0', 'feeCalculation'=>'1', 'lat'=>'41.0723927', 'lng'=>'-81.4516502', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=448612', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'58', 'name'=>'Dimitry Nakhla', 'phone'=>'732-266-4200', 'email'=>'babyloncapitalllc@gmail.com', 'company'=>'Babylon Capital LLC', 'address1'=>'5 Chase Dr', 'address2'=>'', 'city'=>'Morganville', 'st'=>'NJ', 'zip'=>'07751', 'url'=>'', 'minimum_fee'=>'0', 'feeCalculation'=>'1', 'lat'=>'40.3528807', 'lng'=>'-74.3009784', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=457416', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'59', 'name'=>'Michael G. Pento', 'phone'=>'732-772-9500', 'email'=>'mpento@pentoport.com', 'company'=>'Pento Portfolio Strategies, LLC', 'address1'=>'291 Rt 34N', 'address2'=>'Suite D', 'city'=>'Colts Neck', 'st'=>'NJ', 'zip'=>'07722', 'url'=>'http://www.pentoport.com/', 'minimum_fee'=>'0', 'feeCalculation'=>'1', 'lat'=>'40.2805326', 'lng'=>'-74.171263', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=454930', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'60', 'name'=>'Andrew Alter, CPA/ PFS, CFP&reg;, CGMA', 'phone'=>'718-494-6155', 'email'=>'', 'company'=>'Alter Wealth Management, LLC', 'address1'=>'651 Willowbrook Road', 'address2'=>'', 'city'=>'Staten Island', 'st'=>'NY', 'zip'=>'10314', 'url'=>'http://alterwealthmanagement.com', 'minimum_fee'=>'10000', 'feeCalculation'=>'0', 'lat'=>'40.6089591', 'lng'=>'-74.1469035', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=428735', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'61', 'name'=>'Andrew Alter, CPA/ PFS, CFP&reg;, CGMA', 'phone'=>'718-494-6155', 'email'=>'', 'company'=>'Alter Wealth Management, LLC', 'address1'=>'12 Hedgerow Lane', 'address2'=>'', 'city'=>'Manalapan', 'st'=>'NJ', 'zip'=>'07726', 'url'=>'http://alterwealthmanagement.com', 'minimum_fee'=>'10000', 'feeCalculation'=>'0', 'lat'=>'40.268928', 'lng'=>'-74.336786', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=428735', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'62', 'name'=>'Louis R. Terrero', 'phone'=>'609-865-8822', 'email'=>'lterrero@applewoodam.com', 'company'=>'Applewood Asset Management', 'address1'=>'58 West Main St.', 'address2'=>'Suite 201', 'city'=>'Freehold', 'st'=>'NJ', 'zip'=>'07728', 'url'=>'http://www.applewoodam.com', 'minimum_fee'=>'0', 'feeCalculation'=>'1', 'lat'=>'40.258461', 'lng'=>'-74.276255', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=434228', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'63', 'name'=>'Richard L. Eckhoff, MS, CFP&reg;, MPAS&reg;', 'phone'=>'732-224-0151', 'email'=>'', 'company'=>'Monmouth Investment Advisors, LLC', 'address1'=>'1177 West Front St.', 'address2'=>'', 'city'=>'Little Silver', 'st'=>'NJ', 'zip'=>'07738', 'url'=>'', 'minimum_fee'=>'0', 'feeCalculation'=>'1', 'lat'=>'40.3453313', 'lng'=>'-74.1169181', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=440837', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'64', 'name'=>'Charles L. Gorenberg', 'phone'=>'856-428-1575', 'email'=>'chuck@chaslynfinancialgroup.com', 'company'=>'Chaslyn Financial Group', 'address1'=>'51 Haddonfield Rd', 'address2'=>'Suite 210', 'city'=>'Cherry Hill', 'st'=>'NJ', 'zip'=>'08002', 'url'=>'http://www.chaslynfinancialgroup.com', 'minimum_fee'=>'0', 'feeCalculation'=>'0', 'lat'=>'39.9489271', 'lng'=>'-75.0269139', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=418794', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'65', 'name'=>'Ric Edelman', 'phone'=>'866-PLAN-EFS', 'email'=>'info@ricedelman.com', 'company'=>'Edelman Financial Services', 'address1'=>'457 Haddonfield Rd.', 'address2'=>'Suite 310', 'city'=>'Cherry Hill', 'st'=>'NJ', 'zip'=>'08002', 'url'=>'http://www.ricedelman.com', 'minimum_fee'=>'0', 'feeCalculation'=>'0', 'lat'=>'39.9366325', 'lng'=>'-75.0313523', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=444426', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'66', 'name'=>'Ric Edelman', 'phone'=>'866-PLAN-EFS', 'email'=>'info@ricedelman.com', 'company'=>'Edelman Financial Services', 'address1'=>'100 Front St', 'address2'=>'Suite 1375', 'city'=>'Conshohocken', 'st'=>'PA', 'zip'=>'19428', 'url'=>'http://www.ricedelman.com', 'minimum_fee'=>'0', 'feeCalculation'=>'0', 'lat'=>'40.0698608', 'lng'=>'-75.3116896', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=444426', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'67', 'name'=>'Vijar Kohli', 'phone'=>'732-476-4428', 'email'=>'vijar.kohli@goldendoorasset.com', 'company'=>'Golden Door Asset Management LLC', 'address1'=>'221 River St.', 'address2'=>'9th Floor', 'city'=>'Hoboken', 'st'=>'NJ', 'zip'=>'07030', 'url'=>'http://www.goldendoorasset.com', 'minimum_fee'=>'0', 'feeCalculation'=>'1', 'lat'=>'40.738694', 'lng'=>'-74.0277895', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=422030', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'68', 'name'=>'Kevin Saia', 'phone'=>'862-251-4700', 'email'=>'ksaia@s2retirementsolutions.com', 'company'=>'S Squared Retirement Solutions LLC', 'address1'=>'1301 Adams St.', 'address2'=>'Unit 611', 'city'=>'Hoboken', 'st'=>'NJ', 'zip'=>'07030', 'url'=>'http://www.s2retirementsolutions.com', 'minimum_fee'=>'0', 'feeCalculation'=>'1', 'lat'=>'40.7538384', 'lng'=>'-74.0324928', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=440618', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'69', 'name'=>'Anthony Evgenikos', 'phone'=>'973-291-8690', 'email'=>'anthony@ajewealthmanagement.com', 'company'=>'AJE Wealth Management LLC', 'address1'=>'223 Terrace Lake Dr.', 'address2'=>'', 'city'=>'Butler', 'st'=>'NJ', 'zip'=>'07405', 'url'=>'http://www.ajewealthmanagement.com', 'minimum_fee'=>'0', 'feeCalculation'=>'1', 'lat'=>'41.0101758', 'lng'=>'-74.3602983', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=412101', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'70', 'name'=>'Paul Kamke CPA', 'phone'=>'434-566-0474', 'email'=>'invest.paul@kamke.com', 'company'=>'Kamke Investment Strategies INC', 'address1'=>'144 Tuckahoe Farm Lane', 'address2'=>'', 'city'=>'Charlottesville', 'st'=>'VA', 'zip'=>'22901', 'url'=>'http://www.kamke.com', 'minimum_fee'=>'0', 'feeCalculation'=>'1', 'lat'=>'38.104018', 'lng'=>'-78.494941', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=423847', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'71', 'name'=>'Paul Kamke CPA', 'phone'=>'845-358-4677', 'email'=>'invest.paul@kamke.com', 'company'=>'Kamke Investment Strategies INC', 'address1'=>'2 Crosfield Ave', 'address2'=>'Suite 420', 'city'=>'West Nyack', 'st'=>'NY', 'zip'=>'10994', 'url'=>'http://www.kamke.com', 'minimum_fee'=>'0', 'feeCalculation'=>'1', 'lat'=>'41.0930607', 'lng'=>'-73.9770665', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=423847', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'72', 'name'=>'Jonathan D. Caplan', 'phone'=>'732-249-8600', 'email'=>'caplancapital@aol.com', 'company'=>'Caplan Capital Management INC', 'address1'=>'24 North Third Avenue', 'address2'=>'Suite 201', 'city'=>'Highland Park', 'st'=>'NJ', 'zip'=>'08904', 'url'=>'http://www.caplancapital.com', 'minimum_fee'=>'0', 'feeCalculation'=>'1', 'lat'=>'40.4998053', 'lng'=>'-74.4287584', 'brochure'=>'http://docs.wixstatic.com/ugd/8fdf2e_aefbf89ec1724d6e94a84ba5a8e994b1.pdf', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'73', 'name'=>'Nancy Conger CFP', 'phone'=>'973-998-6345', 'email'=>'info@redhookmgmt.com', 'company'=>'Red Hook Management LLC', 'address1'=>'65 Madison Avenue', 'address2'=>'Suite 230', 'city'=>'Morristown', 'st'=>'NJ', 'zip'=>'07960', 'url'=>'http://www.redhookmgmt.com', 'minimum_fee'=>'0', 'feeCalculation'=>'1', 'lat'=>'40.7875289', 'lng'=>'-74.466656', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=430668', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'74', 'name'=>'Bernard Kiely', 'phone'=>'973-455-1894', 'email'=>'bernie@kielycapital.com', 'company'=>'Kiely Capital Management INC', 'address1'=>'51 Dumont Place', 'address2'=>'', 'city'=>'Morristown', 'st'=>'NJ', 'zip'=>'07960', 'url'=>'http://www.kielycapital.com', 'minimum_fee'=>'5000', 'feeCalculation'=>'1', 'lat'=>'40.7954923', 'lng'=>'-74.4781511', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=451774', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'75', 'name'=>'Debra L. Morrison, CFP&reg;, MS, AEP', 'phone'=>'973-709-2244', 'email'=>'Info@EmpoweredRetirement.com', 'company'=>'Empowered Retirement INC', 'address1'=>'89 Headquarters Plaza North', 'address2'=>'Suite 1447', 'city'=>'Morristown', 'st'=>'NJ', 'zip'=>'07960', 'url'=>'http://www.empoweredretirement.com', 'minimum_fee'=>'0', 'feeCalculation'=>'0', 'lat'=>'40.7996366', 'lng'=>'-74.4803535', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=409528', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'76', 'name'=>'Bernhard A. Keil', 'phone'=>'720-319-9703', 'email'=>'bkeil@risconline.net', 'company'=>'Rodeo Investment Services Corporation', 'address1'=>'24068 Matterhorn Dr.', 'address2'=>'', 'city'=>'Indian Hills', 'st'=>'CO', 'zip'=>'80454', 'url'=>'http://www.risconline.net', 'minimum_fee'=>'500', 'feeCalculation'=>'1', 'lat'=>'39.6391912', 'lng'=>'-105.2733585', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=449803', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'77', 'name'=>'Ricky L. Wilson', 'phone'=>'303- 522-3461', 'email'=>'rickwilson@anelucapital.com', 'company'=>'Anelu Capital LLC', 'address1'=>'15175 W. Belleview Avenue', 'address2'=>'', 'city'=>'Morrison', 'st'=>'CO', 'zip'=>'80465', 'url'=>'http://www.anelucapital.com', 'minimum_fee'=>'400', 'feeCalculation'=>'1', 'lat'=>'39.6191850', 'lng'=>'-105.1709960', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=444106', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'78', 'name'=>'Kyle Burris CFP', 'phone'=>'303-697-1891', 'email'=>'Kyle@Sageincomeadvisors.com', 'company'=>'Sage Income Advisors LLC', 'address1'=>'101 Red Rocks Vista Drive', 'address2'=>'', 'city'=>'Morrison', 'st'=>'CO', 'zip'=>'80465', 'url'=>'http://www.sageincomeadvisors.com', 'minimum_fee'=>'0', 'feeCalculation'=>'1', 'lat'=>'39.6517512', 'lng'=>'-105.1946970', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=428669', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'79', 'name'=>'Robert R. Salzman', 'phone'=>'312-520-4799', 'email'=>'rrs@rbsalzman.com', 'company'=>'R.B. Salzman Wealth Management, LLC', 'address1'=>'805 North Chestnut Avenue', 'address2'=>'', 'city'=>'Arlington Heights', 'st'=>'IL', 'zip'=>'60004', 'url'=>'http://www.rbsalzman.com', 'minimum_fee'=>'0', 'feeCalculation'=>'1', 'lat'=>'42.0918715', 'lng'=>'-87.9862490', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=429896', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'80', 'name'=>'Roy W. Brown CFP', 'phone'=>'847-228-1968', 'email'=>'roy@truemanbrown.com', 'company'=>'Trueman Brown LLC', 'address1'=>'1600 Golf Rd.', 'address2'=>'Suite 1200', 'city'=>'Rolling Meadows', 'st'=>'IL', 'zip'=>'60008', 'url'=>'http://www.truemanbrown.com', 'minimum_fee'=>'0', 'feeCalculation'=>'1', 'lat'=>'42.0532128', 'lng'=>'-88.0020497', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=424273', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'81', 'name'=>'Therese Martin, CFP', 'phone'=>'847-524-1232', 'email'=>'therese@martinfm.com', 'company'=>'Martin Financial Management LLC', 'address1'=>'1420 Parker Place', 'address2'=>'', 'city'=>'Elk Grove Village', 'st'=>'IL', 'zip'=>'60007', 'url'=>'http://www.martinfm.com', 'minimum_fee'=>'4000', 'feeCalculation'=>'0', 'lat'=>'41.9966159', 'lng'=>'-88.0368125', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=455641', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'82', 'name'=>'Brian J. Owen', 'phone'=>'847-480-2395', 'email'=>'Brian.J.Owen@bjowm.com', 'company'=>'BJO Wealth Management LLC', 'address1'=>'707 Skokie Blvd.', 'address2'=>'', 'city'=>'Northbrook', 'st'=>'IL', 'zip'=>'60062', 'url'=>'http://www.bjowm.com', 'minimum_fee'=>'1000', 'feeCalculation'=>'1', 'lat'=>'42.1399454', 'lng'=>'-87.7919661', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=410929', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'83', 'name'=>'Bradley S. Joselit', 'phone'=>'847-943-0713', 'email'=>'info@joselitassetmanagement.com', 'company'=>'Joselit Asset Management LLC', 'address1'=>'740 Waukegan Rd.', 'address2'=>'Suite 310', 'city'=>'Deerfield', 'st'=>'IL', 'zip'=>'60015', 'url'=>'http://www.joselitassetmanagement.com', 'minimum_fee'=>'10000', 'feeCalculation'=>'0', 'lat'=>'42.1656029', 'lng'=>'-87.8476566', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=420240', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'84', 'name'=>'MIchael A. Nadler CPA, CFP', 'phone'=>'847-940-4040', 'email'=>'nadler@nadlerfinancial.com', 'company'=>'Nadler Financial Group LLC', 'address1'=>'155 N. Pfingsten Road', 'address2'=>'Suite 160', 'city'=>'Deerfield', 'st'=>'IL', 'zip'=>'60015', 'url'=>'http://www.nadlerfinancial.com', 'minimum_fee'=>'2000', 'feeCalculation'=>'0', 'lat'=>'42.1558975', 'lng'=>'-87.8465221', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=460796', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'85', 'name'=>'Sue Stevens CFP, CFA , CPA', 'phone'=>'847-282-9910', 'email'=>'Suzanne@StevensWealth.com', 'company'=>'Stevens Wealth Management LLC', 'address1'=>'500 Lake Cook Rd.', 'address2'=>'Suite 350', 'city'=>'Deerfield', 'st'=>'IL', 'zip'=>'60015', 'url'=>'http://www.stevenswealth.com', 'minimum_fee'=>'9500', 'feeCalculation'=>'0', 'lat'=>'42.1537123', 'lng'=>'-87.8409702', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=432979', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'86', 'name'=>'Michael D. Bonfrisco JD', 'phone'=>'856-330-4908', 'email'=>'michael@bonfriscolaw.com', 'company'=>'Modern Wealth Coaching LLC', 'address1'=>'1522 Route 38', 'address2'=>'', 'city'=>'Cherry Hill', 'st'=>'NJ', 'zip'=>'08002', 'url'=>'http://www.bonfriscolaw.com', 'minimum_fee'=>'0', 'feeCalculation'=>'1', 'lat'=>'39.9385316', 'lng'=>'-75.0318189', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=424708', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'87', 'name'=>'Richard Louis Mauro, CPA/PFS', 'phone'=>'609-386-6556', 'email'=>'rickmauro@hmmcpas.net', 'company'=>'Strategic Investment Services Inc', 'address1'=>'586 High St.', 'address2'=>'', 'city'=>'Burlington', 'st'=>'NJ', 'zip'=>'08016', 'url'=>'http://www.hmmcpas.com', 'minimum_fee'=>'750', 'feeCalculation'=>'1', 'lat'=>'40.0721790', 'lng'=>'-74.8560319', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=422962', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'88', 'name'=>'Gregory M. Hart, CFP&reg;', 'phone'=>'856-528-4526', 'email'=>'', 'company'=>'Haddon Wealth Management LLC', 'address1'=>'14 Kings Highway West', 'address2'=>'Suite 105', 'city'=>'Haddonfield', 'st'=>'NJ', 'zip'=>'08033', 'url'=>'http://www.haddonwealthmgt.com', 'minimum_fee'=>'0', 'feeCalculation'=>'0', 'lat'=>'39.8956690', 'lng'=>'-75.0366360', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=429707', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'89', 'name'=>'Richard Bell', 'phone'=>'856-482-8700', 'email'=>'Info@planningcapital.com', 'company'=>'Planning Capital Management Corp.', 'address1'=>'30 South Haddon Avenue', 'address2'=>'', 'city'=>'Haddonfield', 'st'=>'NJ', 'zip'=>'08033', 'url'=>'http://www.pcminvestments.com', 'minimum_fee'=>'0', 'feeCalculation'=>'0', 'lat'=>'39.8973170', 'lng'=>'-75.0308830', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=451649', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'90', 'name'=>'Richard Bell', 'phone'=>'610-820-0240', 'email'=>'Info@planningcapital.com', 'company'=>'Planning Capital Management Corp.', 'address1'=>'7540 Windsor Drive', 'address2'=>'Suite 201', 'city'=>'Allentown', 'st'=>'PA', 'zip'=>'18195', 'url'=>'http://www.pcminvestments.com', 'minimum_fee'=>'0', 'feeCalculation'=>'0', 'lat'=>'40.5821691', 'lng'=>'-75.6206821', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=451649', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'91', 'name'=>'Michael P. Pallozzi', 'phone'=>'856-232-2270', 'email'=>'mpallozzi@HFMadvisors.com', 'company'=>'HFM Investment Advisors Inc', 'address1'=>'209 Rowan Blvd.', 'address2'=>'', 'city'=>'Glassboro', 'st'=>'NJ', 'zip'=>'08028', 'url'=>'http://hfmadvisors.com', 'minimum_fee'=>'0', 'feeCalculation'=>'0', 'lat'=>'39.7049620', 'lng'=>'-75.1131760', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=466472', 'bio'=>'']);
		DB::table('advisors')->insert(['created_at'=>now(), 'updated_at'=>now(), 'id'=>'92', 'name'=>'James G. Brandenburgh', 'phone'=>'513-381-0001', 'email'=>'jim@clarifywealth.com', 'company'=>'Clarify Wealth Management', 'address1'=>'50 - Business Way', 'address2'=>'Suite 100', 'city'=>'Cincinnati', 'st'=>'OH', 'zip'=>'45241', 'url'=>'http://www.clarifywealth.com', 'minimum_fee'=>'0', 'feeCalculation'=>'1', 'lat'=>'39.2830053', 'lng'=>'-84.3650893', 'brochure'=>'https://www.adviserinfo.sec.gov/IAPD/Content/Common/crd_iapd_Brochure.aspx?BRCHR_VRSN_ID=428142', 'bio'=>'']);
    }
}
