<?php

use Illuminate\Database\Seeder;

class RatesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'1',  'roof'=>'1000000',  'rate'=>'0.01']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'1',  'roof'=>'2000000',  'rate'=>'0.008']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'1',  'roof'=>'4000000',  'rate'=>'0.006']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'1',  'roof'=>'6000000',  'rate'=>'0.004']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'1',  'roof'=>'10000000', 'rate'=>'0.002']);					
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'2',  'roof'=>'2000000',  'rate'=>'0.007']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'2',  'roof'=>'4000000',  'rate'=>'0.005']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'2',  'roof'=>'10000000', 'rate'=>'0.003']);							
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'3',  'roof'=>'5000000',  'rate'=>'0.0065']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'3',  'roof'=>'10000000', 'rate'=>'0.005']);								
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'4',  'roof'=>'3000000',  'rate'=>'0.01']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'4',  'roof'=>'6000000',  'rate'=>'0.0075']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'4',  'roof'=>'10000000', 'rate'=>'0.005']);							
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'5',  'roof'=>'1000000',  'rate'=>'0.01']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'5',  'roof'=>'5000000',  'rate'=>'0.005']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'5',  'roof'=>'10000000', 'rate'=>'0.0035']);							
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'6',  'roof'=>'1000000',  'rate'=>'0.01']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'6',  'roof'=>'5000000',  'rate'=>'0.0075']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'6',  'roof'=>'10000000', 'rate'=>'0.005']);							
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'7',  'roof'=>'1000000',  'rate'=>'0.008']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'7',  'roof'=>'2000000',  'rate'=>'0.006']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'7',  'roof'=>'3000000',  'rate'=>'0.005']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'7',  'roof'=>'5000000',  'rate'=>'0.004']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'7',  'roof'=>'10000000', 'rate'=>'0.0025']);					
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'8',  'roof'=>'1000000',  'rate'=>'0.015']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'8',  'roof'=>'3000000',  'rate'=>'0.01']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'8',  'roof'=>'10000000', 'rate'=>'0.0075']);							
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'9',  'roof'=>'2000000',  'rate'=>'0.01']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'9',  'roof'=>'5000000',  'rate'=>'0.0075']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'9',  'roof'=>'10000000', 'rate'=>'0.005']);							
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'10', 'roof'=>'1000000',  'rate'=>'0.01']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'10', 'roof'=>'2000000',  'rate'=>'0.008']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'10', 'roof'=>'3000000',  'rate'=>'0.007']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'10', 'roof'=>'4000000',  'rate'=>'0.006']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'10', 'roof'=>'5000000',  'rate'=>'0.005']);					
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'11', 'roof'=>'750000',   'rate'=>'0.0075']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'11', 'roof'=>'1500000',  'rate'=>'0.005']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'11', 'roof'=>'10000000', 'rate'=>'0.0025']);							
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'12', 'roof'=>'10000000', 'rate'=>'0.015']);									
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'13', 'roof'=>'500000',   'rate'=>'0.015']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'13', 'roof'=>'10000000', 'rate'=>'0.01']);								
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'14', 'roof'=>'500000',   'rate'=>'0.0125']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'14', 'roof'=>'2000000',  'rate'=>'0.01']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'14', 'roof'=>'10000000', 'rate'=>'0.008']);							
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'15', 'roof'=>'10000000', 'rate'=>'0.011']);									
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'16', 'roof'=>'500000',   'rate'=>'0.015']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'16', 'roof'=>'1000000',  'rate'=>'0.0125']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'16', 'roof'=>'2000000',  'rate'=>'0.01']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'16', 'roof'=>'4000000',  'rate'=>'0.0075']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'16', 'roof'=>'10000000', 'rate'=>'0.005']);					
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'17', 'roof'=>'500000',   'rate'=>'0.0135']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'17', 'roof'=>'1000000',  'rate'=>'0.011']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'17', 'roof'=>'3000000',  'rate'=>'0.005']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'17', 'roof'=>'10000000', 'rate'=>'0.0025']);						
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'18', 'roof'=>'500000',   'rate'=>'0.01']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'18', 'roof'=>'1000000',  'rate'=>'0.0075']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'18', 'roof'=>'4000000',  'rate'=>'0.005']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'18', 'roof'=>'10000000', 'rate'=>'0.0025']);						
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'19', 'roof'=>'500000',   'rate'=>'0.014']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'19', 'roof'=>'1000000',  'rate'=>'0.01']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'19', 'roof'=>'4000000',  'rate'=>'0.0075']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'19', 'roof'=>'10000000', 'rate'=>'0.005']);						
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'20', 'roof'=>'500000',   'rate'=>'0.01']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'20', 'roof'=>'1000000',  'rate'=>'0.008']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'20', 'roof'=>'3000000',  'rate'=>'0.006']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'20', 'roof'=>'6000000',  'rate'=>'0.005']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'20', 'roof'=>'10000000', 'rate'=>'0.003']);					
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'21', 'roof'=>'10000000', 'rate'=>'0.015']);									
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'22', 'roof'=>'500000',   'rate'=>'0.0099']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'22', 'roof'=>'1000000',  'rate'=>'0.0075']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'22', 'roof'=>'4000000',  'rate'=>'0.007']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'22', 'roof'=>'10000000', 'rate'=>'0.005']);						
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'23', 'roof'=>'250000',   'rate'=>'0.015']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'23', 'roof'=>'500000',   'rate'=>'0.0135']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'23', 'roof'=>'1000000',  'rate'=>'0.0115']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'23', 'roof'=>'2000000',  'rate'=>'0.01']);						
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'24', 'roof'=>'100000',   'rate'=>'0.012']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'24', 'roof'=>'250000',   'rate'=>'0.0095']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'24', 'roof'=>'500000',   'rate'=>'0.0085']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'24', 'roof'=>'750000',   'rate'=>'0.007']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'24', 'roof'=>'1250000',  'rate'=>'0.006']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'24', 'roof'=>'2250000',  'rate'=>'0.005']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'24', 'roof'=>'10000000', 'rate'=>'0.004']);			
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'25', 'roof'=>'5250000',  'rate'=>'0.021']);									
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'26', 'roof'=>'100000',   'rate'=>'0.02']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'26', 'roof'=>'500000',   'rate'=>'0.01']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'26', 'roof'=>'10000000', 'rate'=>'0.005']);							
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'27', 'roof'=>'5500000',  'rate'=>'0.006']);									
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'28', 'roof'=>'500000',   'rate'=>'0.012']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'28', 'roof'=>'1500000',  'rate'=>'0.01']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'28', 'roof'=>'3500000',  'rate'=>'0.008']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'28', 'roof'=>'5500000',  'rate'=>'0.006']);						
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'29', 'roof'=>'100000',   'rate'=>'0.015']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'29', 'roof'=>'400000',   'rate'=>'0.0125']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'29', 'roof'=>'10000000', 'rate'=>'0.01']);							
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'30', 'roof'=>'50000',    'rate'=>'0.0165']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'30', 'roof'=>'100000',   'rate'=>'0.015']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'30', 'roof'=>'250000',   'rate'=>'0.013']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'30', 'roof'=>'500000',   'rate'=>'0.0115']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'30', 'roof'=>'1000000',  'rate'=>'0.01']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'30', 'roof'=>'2500000',  'rate'=>'0.009']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'30', 'roof'=>'10000000', 'rate'=>'0.008']);			
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'31', 'roof'=>'500000',   'rate'=>'0.015']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'31', 'roof'=>'1000000',  'rate'=>'0.0125']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'31', 'roof'=>'10000000', 'rate'=>'0.01']);							
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'32', 'roof'=>'1000000',  'rate'=>'0.013']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'32', 'roof'=>'2500000',  'rate'=>'0.01']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'32', 'roof'=>'3000000',  'rate'=>'0.0075']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'32', 'roof'=>'10000000', 'rate'=>'0.005']);						
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'33', 'roof'=>'100000',   'rate'=>'0.015']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'33', 'roof'=>'500000',   'rate'=>'0.0125']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'33', 'roof'=>'1000000',  'rate'=>'0.01']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'33', 'roof'=>'2500000',  'rate'=>'0.0075']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'33', 'roof'=>'10000000', 'rate'=>'0.005']);					
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'34', 'roof'=>'1000000',  'rate'=>'0.01']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'34', 'roof'=>'3000000',  'rate'=>'0.0085']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'34', 'roof'=>'10000000', 'rate'=>'0.0075']);							
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'35', 'roof'=>'250000',   'rate'=>'0.015']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'35', 'roof'=>'500000',   'rate'=>'0.0135']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'35', 'roof'=>'1000000',  'rate'=>'0.0125']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'35', 'roof'=>'1500000',  'rate'=>'0.01']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'35', 'roof'=>'3000000',  'rate'=>'0.0075']);					
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'36', 'roof'=>'250000',   'rate'=>'0.02']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'36', 'roof'=>'500000',   'rate'=>'0.0175']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'36', 'roof'=>'1000000',  'rate'=>'0.015']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'36', 'roof'=>'5000000',  'rate'=>'0.0125']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'36', 'roof'=>'10000000', 'rate'=>'0.01']);					
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'37', 'roof'=>'100000',   'rate'=>'0.0175']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'37', 'roof'=>'250000',   'rate'=>'0.0165']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'37', 'roof'=>'500000',   'rate'=>'0.015']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'37', 'roof'=>'750000',   'rate'=>'0.0135']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'37', 'roof'=>'1000000',  'rate'=>'0.0125']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'37', 'roof'=>'2500000',  'rate'=>'0.01']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'37', 'roof'=>'3000000',  'rate'=>'0.009']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'37', 'roof'=>'4000000',  'rate'=>'0.008']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'37', 'roof'=>'5000000',  'rate'=>'0.007']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'37', 'roof'=>'10000000', 'rate'=>'0.006']);
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'38', 'roof'=>'1000000',  'rate'=>'0.01']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'38', 'roof'=>'3000000',  'rate'=>'0.008']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'38', 'roof'=>'5000000',  'rate'=>'0.006']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'38', 'roof'=>'10000000', 'rate'=>'0.005']);						
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'39', 'roof'=>'100000',   'rate'=>'0.014']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'39', 'roof'=>'250000',   'rate'=>'0.013']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'39', 'roof'=>'500000',   'rate'=>'0.012']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'39', 'roof'=>'1000000',  'rate'=>'0.011']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'39', 'roof'=>'2500000',  'rate'=>'0.01']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'39', 'roof'=>'10000000', 'rate'=>'0.009']);				
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'40', 'roof'=>'2500000',  'rate'=>'0.0125']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'40', 'roof'=>'5000000',  'rate'=>'0.01']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'40', 'roof'=>'10000000', 'rate'=>'0.0085']);							
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'41', 'roof'=>'1000000',  'rate'=>'0.015']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'41', 'roof'=>'5000000',  'rate'=>'0.0125']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'41', 'roof'=>'10000000', 'rate'=>'0.01']);							
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'42', 'roof'=>'1000000',  'rate'=>'0.02']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'42', 'roof'=>'2000000',  'rate'=>'0.015']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'42', 'roof'=>'10000000', 'rate'=>'0.01']);							
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'43', 'roof'=>'250000',   'rate'=>'0.0125']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'43', 'roof'=>'1000000',  'rate'=>'0.0115']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'43', 'roof'=>'3000000',  'rate'=>'0.0105']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'43', 'roof'=>'5000000',  'rate'=>'0.0095']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'43', 'roof'=>'10000000', 'rate'=>'0.0085']);					
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'44', 'roof'=>'100000',   'rate'=>'0.005']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'44', 'roof'=>'250000',   'rate'=>'0.00375']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'44', 'roof'=>'1000000',  'rate'=>'0.003125']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'44', 'roof'=>'2000000', 'rate'=>'0.0025']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'44', 'roof'=>'5000000',  'rate'=>'0.00225']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'44', 'roof'=>'10000000', 'rate'=>'0.002']);				
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'45', 'roof'=>'2500000',  'rate'=>'0.02']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'45', 'roof'=>'5000000',  'rate'=>'0.015']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'45', 'roof'=>'10000000', 'rate'=>'0.01']);							
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'46', 'roof'=>'1000000',  'rate'=>'0.01']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'46', 'roof'=>'10000000', 'rate'=>'0.0085']);								
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'47', 'roof'=>'100000',   'rate'=>'0.0175']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'47', 'roof'=>'250000',   'rate'=>'0.015']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'47', 'roof'=>'500000',   'rate'=>'0.0125']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'47', 'roof'=>'10000000', 'rate'=>'0.01']);						
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'48', 'roof'=>'1000000',  'rate'=>'0.01']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'48', 'roof'=>'2000000',  'rate'=>'0.009']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'48', 'roof'=>'5000000',  'rate'=>'0.007']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'48', 'roof'=>'8000000',  'rate'=>'0.005']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'48', 'roof'=>'10000000', 'rate'=>'0.004']);					
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'49', 'roof'=>'500000',   'rate'=>'0.02']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'49', 'roof'=>'750000',   'rate'=>'0.015']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'49', 'roof'=>'1000000',  'rate'=>'0.012']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'49', 'roof'=>'1500000',  'rate'=>'0.01']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'49', 'roof'=>'2000000',  'rate'=>'0.009']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'49', 'roof'=>'2500000',  'rate'=>'0.008']);				
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'50', 'roof'=>'500000',   'rate'=>'0.0125']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'50', 'roof'=>'50000000', 'rate'=>'0.01']);								
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'51', 'roof'=>'1000000',  'rate'=>'0.015']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'51', 'roof'=>'5000000',  'rate'=>'0.01']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'51', 'roof'=>'10000000', 'rate'=>'0.0075']);							
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'52', 'roof'=>'500000',   'rate'=>'0.02']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'52', 'roof'=>'1000000',  'rate'=>'0.0175']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'52', 'roof'=>'5000000',  'rate'=>'0.015']);							
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'53', 'roof'=>'2000000',  'rate'=>'0.005']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'53', 'roof'=>'10000000', 'rate'=>'0.0025']);								
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'54', 'roof'=>'500000',   'rate'=>'0.0075']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'54', 'roof'=>'1000000',  'rate'=>'0.005']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'54', 'roof'=>'10000000', 'rate'=>'0.0025']);							
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'55', 'roof'=>'100000',   'rate'=>'0.02']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'55', 'roof'=>'500000',   'rate'=>'0.0175']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'55', 'roof'=>'750000',   'rate'=>'0.015']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'55', 'roof'=>'1000000',  'rate'=>'0.0125']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'55', 'roof'=>'10000000', 'rate'=>'0.01']);					
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'56', 'roof'=>'250000',   'rate'=>'0.01']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'56', 'roof'=>'500000',   'rate'=>'0.0095']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'56', 'roof'=>'1000000',  'rate'=>'0.009']);							
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'57', 'roof'=>'1000000',  'rate'=>'0.0125']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'57', 'roof'=>'10000000', 'rate'=>'0.01']);								
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'58', 'roof'=>'10000000', 'rate'=>'0.0125']);									
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'59', 'roof'=>'1000000',  'rate'=>'0.015']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'59', 'roof'=>'2500000',  'rate'=>'0.0135']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'59', 'roof'=>'10000000', 'rate'=>'0.0115']);							
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'60', 'roof'=>'500000',   'rate'=>'0.0125']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'60', 'roof'=>'1000000',  'rate'=>'0.009']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'60', 'roof'=>'2000000',  'rate'=>'0.007']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'60', 'roof'=>'3000000',  'rate'=>'0.005']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'60', 'roof'=>'5000000',  'rate'=>'0.004']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'60', 'roof'=>'10000000', 'rate'=>'0.0035']);				
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'61', 'roof'=>'500000',   'rate'=>'0.0125']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'61', 'roof'=>'1000000',  'rate'=>'0.009']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'61', 'roof'=>'2000000',  'rate'=>'0.007']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'61', 'roof'=>'3000000',  'rate'=>'0.005']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'61', 'roof'=>'5000000',  'rate'=>'0.004']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'61', 'roof'=>'10000000', 'rate'=>'0.0035']);				
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'62', 'roof'=>'500000',   'rate'=>'0.015']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'62', 'roof'=>'750000',   'rate'=>'0.0125']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'62', 'roof'=>'1000000',  'rate'=>'0.01']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'62', 'roof'=>'10000000', 'rate'=>'0.0075']);						
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'63', 'roof'=>'25000',    'rate'=>'0.025']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'63', 'roof'=>'50000',    'rate'=>'0.0225']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'63', 'roof'=>'100000',   'rate'=>'0.02']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'63', 'roof'=>'250000',   'rate'=>'0.0175']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'63', 'roof'=>'500000',   'rate'=>'0.015']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'63', 'roof'=>'1000000',  'rate'=>'0.0125']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'63', 'roof'=>'5000000',  'rate'=>'0.01']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'63', 'roof'=>'10000000', 'rate'=>'0.0075']);		
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'64', 'roof'=>'1000000',  'rate'=>'0.005']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'64', 'roof'=>'5000000',  'rate'=>'0.0045']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'64', 'roof'=>'10000000', 'rate'=>'0.004']);							
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'65', 'roof'=>'150000',   'rate'=>'0.02']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'65', 'roof'=>'400000',   'rate'=>'0.0165']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'65', 'roof'=>'750000',   'rate'=>'0.0125']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'65', 'roof'=>'1000000',  'rate'=>'0.01']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'65', 'roof'=>'3000000',  'rate'=>'0.0075']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'65', 'roof'=>'10000000', 'rate'=>'0.006']);				
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'66', 'roof'=>'150000',   'rate'=>'0.02']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'66', 'roof'=>'400000',   'rate'=>'0.0165']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'66', 'roof'=>'750000',   'rate'=>'0.0125']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'66', 'roof'=>'1000000',  'rate'=>'0.01']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'66', 'roof'=>'3000000',  'rate'=>'0.0075']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'66', 'roof'=>'10000000', 'rate'=>'0.006']);				
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'67', 'roof'=>'10000000', 'rate'=>'0.01']);									
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'68', 'roof'=>'500000',   'rate'=>'0.015']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'68', 'roof'=>'1000000',  'rate'=>'0.01']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'68', 'roof'=>'5000000',  'rate'=>'0.0085']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'68', 'roof'=>'10000000', 'rate'=>'0.005']);						
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'69', 'roof'=>'500000',   'rate'=>'0.0175']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'69', 'roof'=>'1000000',  'rate'=>'0.015']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'69', 'roof'=>'1500000',  'rate'=>'0.0125']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'69', 'roof'=>'2000000',  'rate'=>'0.011']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'69', 'roof'=>'3000000',  'rate'=>'0.01']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'69', 'roof'=>'5000000',  'rate'=>'0.0075']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'69', 'roof'=>'10000000', 'rate'=>'0.005']);			
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'70', 'roof'=>'300000',   'rate'=>'0.0125']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'70', 'roof'=>'2000000',  'rate'=>'0.01']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'70', 'roof'=>'4000000',  'rate'=>'0.0075']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'70', 'roof'=>'10000000', 'rate'=>'0.005']);						
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'71', 'roof'=>'300000',   'rate'=>'0.0125']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'71', 'roof'=>'2000000',  'rate'=>'0.01']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'71', 'roof'=>'4000000',  'rate'=>'0.0075']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'71', 'roof'=>'10000000', 'rate'=>'0.005']);						
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'72', 'roof'=>'100000',   'rate'=>'0.015']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'72', 'roof'=>'200000',   'rate'=>'0.01375']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'72', 'roof'=>'300000',   'rate'=>'0.0125']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'72', 'roof'=>'500000',  'rate'=>'0.01125']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'72', 'roof'=>'10000000', 'rate'=>'0.01']);					
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'73', 'roof'=>'2000000',  'rate'=>'0.01']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'73', 'roof'=>'5000000',  'rate'=>'0.0085']);								
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'74', 'roof'=>'1000000',  'rate'=>'0.01']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'74', 'roof'=>'2000000',  'rate'=>'0.0075']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'74', 'roof'=>'10000000', 'rate'=>'0.005']);							
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'75', 'roof'=>'1000000',  'rate'=>'0.01']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'75', 'roof'=>'3000000',  'rate'=>'0.0085']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'75', 'roof'=>'5000000',  'rate'=>'0.0075']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'75', 'roof'=>'10000000', 'rate'=>'0.006']);						
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'76', 'roof'=>'500000',   'rate'=>'0.01']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'76', 'roof'=>'1000000',  'rate'=>'0.0095']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'76', 'roof'=>'3000000',  'rate'=>'0.009']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'76', 'roof'=>'5000000',  'rate'=>'0.0085']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'76', 'roof'=>'10000000', 'rate'=>'0.0075']);					
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'77', 'roof'=>'1000000',  'rate'=>'0.008']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'77', 'roof'=>'2000000',  'rate'=>'0.0065']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'77', 'roof'=>'3000000',  'rate'=>'0.005']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'77', 'roof'=>'5000000',  'rate'=>'0.0036']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'77', 'roof'=>'10000000', 'rate'=>'0.0024']);					
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'78', 'roof'=>'500000',   'rate'=>'0.01']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'78', 'roof'=>'1000000',  'rate'=>'0.008']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'78', 'roof'=>'2000000',  'rate'=>'0.006']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'78', 'roof'=>'3000000',  'rate'=>'0.005']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'78', 'roof'=>'10000000', 'rate'=>'0.006']);					
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'79', 'roof'=>'100000',   'rate'=>'0.015']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'79', 'roof'=>'200000',   'rate'=>'0.01']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'79', 'roof'=>'1000000',  'rate'=>'0.005']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'79', 'roof'=>'5000000',  'rate'=>'0.004']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'79', 'roof'=>'10000000', 'rate'=>'0.003']);					
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'80', 'roof'=>'500000',   'rate'=>'0.01']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'80', 'roof'=>'3000000',  'rate'=>'0.0075']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'80', 'roof'=>'5000000',  'rate'=>'0.0065']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'80', 'roof'=>'7000000',  'rate'=>'0.005']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'80', 'roof'=>'10000000', 'rate'=>'0.0025']);					
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'81', 'roof'=>'1000000',  'rate'=>'0.01']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'81', 'roof'=>'10000000', 'rate'=>'0.0075']);								
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'82', 'roof'=>'1000000',  'rate'=>'0.01']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'82', 'roof'=>'3000000',  'rate'=>'0.009']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'82', 'roof'=>'5000000',  'rate'=>'0.008']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'82', 'roof'=>'10000000', 'rate'=>'0.006']);						
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'83', 'roof'=>'2000000',  'rate'=>'0.01']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'83', 'roof'=>'5000000',  'rate'=>'0.009']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'83', 'roof'=>'10000000', 'rate'=>'0.008']);							
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'84', 'roof'=>'1000000',  'rate'=>'0.01']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'84', 'roof'=>'3000000',  'rate'=>'0.0085']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'84', 'roof'=>'5000000',  'rate'=>'0.007']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'84', 'roof'=>'10000000', 'rate'=>'0.005']);						
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'85', 'roof'=>'1000000',  'rate'=>'0.0095']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'85', 'roof'=>'2000000',  'rate'=>'0.008']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'85', 'roof'=>'5000000',  'rate'=>'0.007']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'85', 'roof'=>'10000000', 'rate'=>'0.005']);						
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'86', 'roof'=>'10000000', 'rate'=>'0.0099']);									
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'87', 'roof'=>'50000',    'rate'=>'0.012']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'87', 'roof'=>'300000',   'rate'=>'0.01']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'87', 'roof'=>'10000000', 'rate'=>'0.008']);							
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'88', 'roof'=>'500000',   'rate'=>'0.01']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'88', 'roof'=>'1000000',  'rate'=>'0.0085']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'88', 'roof'=>'2000000',  'rate'=>'0.007']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'88', 'roof'=>'5000000', 'rate'=>'0.0055']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'88', 'roof'=>'10000000', 'rate'=>'0.004']);					
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'89', 'roof'=>'50000',    'rate'=>'0.015']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'89', 'roof'=>'100000',   'rate'=>'0.0125']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'89', 'roof'=>'1000000',  'rate'=>'0.01']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'89', 'roof'=>'2000000', 'rate'=>'0.008']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'89', 'roof'=>'5000000',  'rate'=>'0.007']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'89', 'roof'=>'10000000', 'rate'=>'0.005']);				
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'90', 'roof'=>'50000',    'rate'=>'0.015']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'90', 'roof'=>'100000',   'rate'=>'0.0125']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'90', 'roof'=>'1000000',  'rate'=>'0.01']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'90', 'roof'=>'2000000', 'rate'=>'0.008']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'90', 'roof'=>'5000000',  'rate'=>'0.007']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'90', 'roof'=>'10000000', 'rate'=>'0.005']);				
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'91', 'roof'=>'500000',   'rate'=>'0.0099']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'91', 'roof'=>'1000000',  'rate'=>'0.0075']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'91', 'roof'=>'3000000',  'rate'=>'0.005']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'91', 'roof'=>'10000000', 'rate'=>'0.0025']);						
		DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'92', 'roof'=>'150000',   'rate'=>'0.0135']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'92', 'roof'=>'500000',   'rate'=>'0.012']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'92', 'roof'=>'1000000',  'rate'=>'0.01']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'92', 'roof'=>'2000000', 'rate'=>'0.009']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'92', 'roof'=>'3000000',  'rate'=>'0.008']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'92', 'roof'=>'5000000',  'rate'=>'0.0075']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'92', 'roof'=>'7000000',  'rate'=>'0.007']);	DB::table('rates')->insert(['created_at'=>now(), 'updated_at'=>now(), 'advisor_id'=>'92', 'roof'=>'10000000', 'rate'=>'0.0065']);		
    }
}
